version: '3.3'

services: 
    web:
        build: .
        command: python /code/manage.py runserver 0.0.0.0:8000
        environment: 
            - SECRET_KEY=QWhddhj3002jdndjieee9nnd
            - DEBUG=1
            - STRIPE_TEST_PUBLISHABLE_KEY=pk_test_Lxd3172yhsMdvG4sIDMwVly6003M9jyoVU            
            - STRIPE_TEST_SECRET_KEY=sk_test_eJ9uXGSxRDzIatyLcBDwD7qo00srJoLqHD
        volumes: 
            - .:/code 
        ports: 
            - 8000:8000
        depends_on: 
            - db

    db:
        image: postgres:11

        volumes: 
            - postgres_data:/var/lib/postgresql/data/

volumes: 
    postgres_data:
